# Generated by Django 5.1 on 2024-09-01 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('villa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='villa',
            name='renter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='renter_customer', to='user.customer'),
        ),
    ]
