# Generated by Django 5.1 on 2024-09-01 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('villa', '0002_villa_renter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='villa',
            name='renter',
        ),
        migrations.AddField(
            model_name='villa',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renter', to='user.customer')),
                ('villa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rented_villa', to='villa.villa')),
            ],
        ),
    ]
