# Generated by Django 5.1 on 2024-09-15 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villa', '0003_remove_villa_renter_villa_description_rent'),
    ]

    operations = [
        migrations.AddField(
            model_name='villa',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='villa_images/'),
        ),
    ]
